import {config} from "@fortawesome/fontawesome-svg-core";
import type {Metadata} from "next";
import {ReactNode} from "react";
import "./globals.scss";
import {Providers} from "./Providers";

config.autoAddCss = false;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({children}: RootLayoutProps) {
  return (
    <html lang="it">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
